# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IOSTest_Arpit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift', '~>10'

  # Pods for IOSTest_Arpit

end
